VkOpt/VkOpt

content_script.js
source/vk_face.js
source/vk_lib.js
source/vk_main.js
source/vk_media.js
source/vk_page.js
source/vk_settings.js
source/vk_skinman.js
source/vk_txtedit.js

У некоторых переменных забыли написать `var `, в результате чего локальные переменные стали глобальными. Их удаление из глобальной области сэкономит память.

Глобальные поневоле

---

source/vk_face.js
source/vk_lib.js
source/vk_main.js
source/vk_media.js
source/vk_page.js
source/vk_settings.js
source/vk_skinman.js
source/vk_txtedit.js

Локальные переменные создаются, им присваивается какое-то значение, но потом не используется.
А также удалены неиспользуемые аргументы функций (по сути те же локальные переменные).
И еще по поводу переменной messer - не стал удалять, потому что очень похоже на опечатку.

Неиспользуемые локальные переменные

---

source/vk_media.js

Добавлена отдельная кнопка для скачивания аудиозаписей через wget на Linux.
Кстати, серенькие кнопочки исчезли и стали синими. (vk изменил свой CSS)

Разделение кнопок wget для Windows и Linux

---

source/vk_face.js
source/vk_lib.js
source/vk_main.js
source/vk_media.js
source/vk_page.js
source/vk_settings.js
source/vk_skinman.js
source/vkopt.js

* return последней строчкой - бесполезен
* необязательные переменные
* необязательные точки с запятой

необяательные элементы

---

source/vk_lib.js
source/vk_main.js
source/vk_media.js
source/vk_page.js
source/vk_settings.js

* присвоенное значение никогда не используется
* опечатка - вместо i написана k, которая не определена

неиспользуеммые присваивания

---

source/vk_media.js

удаление никогда не выполняемого кода

по поводу #92

---

source/vk_page.js

Исправление ошибки, когда включена функция "показывать все комментарии" и в ленте появляется ссылка "Показать ещё 1 похожую запись" - она, оказывается, имеет такой же класс, что и "показать комменатрии".

Дополнение к #87 ("показывать все комментарии")

---

source/vk_main.js
source/vkopt.js

Экстра-настройка есть, но настроить ее нельзя, потому что нет галочки. Надо или галочку добавить, или удалить эту настройку.

ненастраиваемая настройка

---

source/vk_main.js
source/vklang.js

Добавлена инфа о пользователях, регистронезависимость и разделяющая штука:
PS. так как тот пулл-реквест слит, переоткрыть его не могу. создаю новый.

дополнение к #98 (поиск по темам)

---

source/vk_media.js

только в href нужен javascript:

onclick можно бeз javascript

---

source/vk_resources.js

В качестве условия используется присваивание. Это либо опечатка == , либо ошибка, потому что какой то странный код получается.

присваивание в if

---

source/vklang.js

English version for phrases "seUseHtml5ForVideo", "infoOnlyForCompatible"

English version updated

---

background.js
content_script.js

В бэкграундных скриптах исправлены небольшие ошибки, типа лишних/отсутствующих точек с запятой, ненужных переменных, упрощения условий.

небольшие исправления бэкграунда

---

source/vk_face.js

Добавил новую ссылку на "Мои Видео" во всплывающем меню, поскольку теперь по '/video'  у них ВидеоКаталог аля ютуб. Думаю для него стоит добавить отдельный линк, но подальше...

Новый линк на "Мои Видео"

---

source/vk_page.js

получение величины текущей прокрутки страницы теперь происходит через кроссбраузерную ВК-функцию (из common.js).

Исправлено отображение кнопок листания постов

---

source/vk_page.js

На опере не работала кнопка "предыдущий"

Дополнение к #130: кроссбраузерная кнопка "предыдущий"

---

source/vk_main.js

Исправление функции #105 чтобы FLV хоть через флеш можно было посмотреть

Всегда показывать FLV через Flash

---

source/vk_users.js

Во всплывающих профилях встречается undefined

undefined в профилях

---

source/vk_face.js
source/vk_lib.js
source/vk_main.js
source/vk_media.js
source/vk_page.js
source/vk_settings.js
source/vk_skinman.js
source/vk_users.js
source/vkopt.js

Заменены выражения типа
`variable ? variable : default_value`
на аналогичное
`variable || default_value`
потому что читается легче и, теоретически, работает быстрее

Замена тернарного оператора логическим

---

source/vk_media.js

У некоторых людей скачивание фотографий из диалога зависает на 90%. Данный патч решает проблему.

Исправление для #120 (скачивание фоток из диалога)

---

source/vk_media.js

Видео не добавлено, потому что wkview.php не возвращает прямых ссылок, а только id. Это значит надо будет асинхронно запрашивать ссылки по каждому видео, и потом еще ждать, когда все ссылки вернутся. Не хочу с этим возиться, да и не нужна мне эта функция, поэтому пока что при нажатии на "ссылки" в разделе Видео будет появляться алерт "Not supported".

В функции скачивания материалов беседы добавлены аудио и документы

---

source/vk_main.js

Я тут попробовал скачать все вики-страницы сообщества LIVE, и обнаружил несколько ошибок. Теперь исправил.

#149 - исправление для большого количества страниц

---

source/vk_media.js

По поводу скачивания фоток в ZIP архив.
Сейчас фотографии скачиваются через бекграунд, потому что не всегда у jpg файлов возвращается заголовок CORS. И из-за этого идёт очень большое потребление оперативной памяти. Чтобы скачать архив 1 мб у меня потребление увеличивается на 80-100 мб. Я думаю, что это из-за того, что в postMessage перебрасывается Uint8Array, а перед этим он еще и копируется 2 раза.
Я изменил код, чтобы скачка шла через обычный xhr, а при отсутствии заголовка CORS чтобы использовался прокси (как [здесь](https://github.com/VkOpt/VkOpt/pull/149#issuecomment-111124989)). И потребление памяти значительно снизилось, для того же архива 1 мб оно стало около 10 мб.
Если прокси будет недоступен, скачивание пойдет как и раньше - через бекграунд.

#76 - Оптимизация потребления оперативки

---

source/vk_media.js

В фотоальбоме сейчас вот так, без разделителя, некрасиво:

Разделитель в альбоме

---

source/vk_page.js

В #130 чтобы кнопки отображались на страницах вида /wall12345

Отображать кнопки листания постов на странице стены

---

source/vk_page.js
source/vklang.js

На странице группы при нажатии на кнопку "сортировать по лайкам" надпись меняется на "Сортировать по дате", и при последующем нажатии записи на стене сортируются по дате, т.е. как обычно и надпись меняется на "сортировать по лайкам"  . И так далее.

Повторная сортировка записей на стене возвращает порядок обратно

---

source/vk_users.js
source/vklang.js

Для групп, пабликов и событий теперь тоже есть всплывающий профиль (по наведению на аватарку либо по <kbd>></kbd> в юзер-меню)

Всплывающий профиль для групп

---

source/vk_face.js
source/vk_lib.js
source/vk_main.js
source/vk_media.js
source/vk_page.js
source/vk_resources.js
source/vk_settings.js
source/vk_skinman.js
source/vk_users.js
source/vkopt.js

Предлагаю выводить отладочные сообщения в консоль только  если включен режим отладки (vk_DEBUG).
Изменение не концептуальное, но просто поможет видеть сообщения в консоли только от Вконтакте.

console.log только при включенном vk_DEBUG

---

source/vk_users.js

упрощены регулярки и добавлена поддержка встреч (event)

Улучшение getGidUid

---

source/vk_main.js
source/vk_settings.js
source/vklang.js
source/vkopt.js

Вынес настройку в виде галочки:
Я написал "конференций", чтобы не было повтора чат-чат. Так-то он конечно чат, но и миничат тоже чат.

Вынесение в настройки DISABLE_CHATS_TYPING_NOTIFY

---

source/vk_settings.js
source/vklang.js

В настройках, где "подписка на стены", к текстовому полю добавлен placeholder c подсказкой "Ссылка или id владельца"

Подсказка для текстового поля менеджера стен

---

source/vk_main.js

Дополнение для #181, чтобы работало на всех браузерах

Исправление #163 для некоторых браузеров

---

source/vk_media.js

#140  Выполнено!
Правда, не сделал настройку. Но там вроде не должно особо мешаться: Inj нет, только доп. событие при переключении вкладок с собеседниками

Вставка картинок из буфера в Firefox

---

source/vk_media.js

Теперь в списке, который открывается по нажатию на "музыка" в шапке, тоже есть кнопки скачивания.
PS. удаление пробелов не я делал, это видимо PhpStorm сама. убрать их из коммита не получилось.

Кнопки скачивания аудио во всплывающем плеере

---

source/vk_media.js

Оказалось, что на Chrome не срабатывает  `onreadystatechange` при ошибке Cross-Origin, поэтому не работает переключение на CORS-прокси.
Добавлено событие `onerror`, которое срабатывает. Теперь работает. Но ошибки в консоли всё равно есть, это нормально.

Исправление скачивания ZIP с фотографиями

---

source/vk_media.js

1. Удален неиспользуемый аргумент `to` и его бессмысленная проверка
1. Теперь ссылка "Добавить в плейлист" показывается всегда, а когда невозможно добавить - просто воспроизводится трек.
1. Теперь можно добавлять аудио откуда угодно, не обязательно из всплывающего плеера. 
1. Разрешается добавление в плейлист трека, который там уже есть. В этом случае он будет перемещён. И info будет браться из плейлиста, а не из DOM.
1. Удалён устаревший код

Улучшение функции добавления аудио в плейлист

---

source/vk_main.js

https://github.com/VkOpt/VkOpt/pull/181#issuecomment-134962703 выполнено

Еще одно исправление для #163

---

background.js
builds/firefoxJetpack/resources/vkopt/lib/main.js

Я налажал в #184, там иногда `data instanceof Array` возвращает `false` даже если на самом деле data - это массив. И соответственно, массивы опять сериализуются.

Исправление для #184

---

source/vk_main.js

Исправление для #196

---

source/vk_media.js

Скачивание Coub

---

source/vk_users.js

У сообщества https://vk.com/jd_dresses появился раздел "товары", и там исправлено:
* не показывать стрелочку юзер-меню около ссылок на "товары"
* стрелочка юзер-меню не на новой строке на странице товара
* не показывать всплывашку при наведении на ссылки на товары

Фиксы в связи с введением маркета

---

source/vk_media.js

vkAudioEd.Delete содержит методы, реализованные стандартными средствами Вконтакте: удаление аудиозаписи и восстановление.
Можно удалить.

удаление vkAudioEd

---

source/vk_page.js

Исправление для сломавшихся "друзей онлайн"

Исправление online -> Online

---

source/vk_page.js
source/vk_settings.js

Всё равно статус иконки давно не работают. Или стоит выпилить весь скрипт?

удаление иконки статуса скайпа

---

source/vk_users.js
source/vkopt.js

Позволяет просматривать все записи, в которых упомянули пользователя/группу.
Источник: https://vk.com/wall-2158488_233149

Пункт в пользовательском меню "Упоминания"

---

source/vk_media.js

Когда нажимаешь "Действия" - "ссылки" на странице альбомов, некоторое время в начале висит пустое окно (альбомы подгружаются). Надо, чтобы там была анимация загрузки.

Анимация в начале при скачивании всех альбомов

---

source/vk_media.js

При скачивании ZIP с фотографиями использовать `NUM_ORIGNAME` для именования файлов

Имена для ZIP

---

source/vk_face.js

Исправление для #221

---

source/vk_main.js

Я опять наступил на грабли из #172. Ютубовский плеер работает только в слое, а надо, чтобы и в новостях тоже.

Youtube плеер в новостях

---

source/vk_face.js
source/vk_main.js

Исчезла кнопка "ответить" в диалогах.
Из-за того, что добавили два дочерних элемента, и `mid` была пуста

Исправление кнопки "ответить" и функций даты/времени в диалогах

---

source/vk_page.js

В продолжение #240
Удаление неиспользуемого кода в модуле дизлайков.

Удаление устаревшего кода dk

---

source/vk_main.js

Исправление для #221 
Чтобы можно было кидать файлы в окно

Исправление функции перетаскивания в окно

---

source/vk_media.js
source/vk_users.js

Удаление этих переменных и функций никак не повлияет на работоспособность.

Неиспользуемые переменные и функции

---

source/vk_users.js

Убираем лишнюю кнопку меню для групповых диалогов
ну вот это вот всё

Исправление всвязи с введением диалога с группой

---

source/vk_users.js

Быстрый доступ к написанию сообщения группе через выпадающее меню

Диалог с группой в выпадающем меню

---

source/vk_face.js

Исправление функции просмотра в плеере youtube

---

source/vk_users.js
source/vklang.js

Во всплывающем профиле добавлена дата регистрации во Вконтакте.

Дата регистрации во всплывающем профиле

---

source/vk_users.js

Добавлены VKFeed для iPhone и Kate Mobile

Дополнен список id клиентов

---

source/vk_face.js
source/vk_settings.js

Дизайн списка стен

---

source/vk_users.js

Сейчас ссылка "Подарки" в пользовательском меню ведет на отдельную страницу, даже без аякса. Я предлагаю показывать подарки во всплывающем окне.

Подарки во всплывающем окне

---

source/vk_users.js

В #266 я сделал сворачиваемым окно всплывающего профиля, но смотрится оно в таком виде не очень, плюс не работает определение даты регистрации, так что я откатываю это изменение.

Меньше сворачиваемых окон

---

source/vk_media.js

Исправление проблемы со скрыванием рекомендуемых аудио

---

source/vk_media.js

Функция скачивания всех материалов из беседы #120 переписана с использованием нового метода API `messages.getHistoryAttachments`.
Видео так и не работает, т.к. возвращаются только id видео, без ссылок.

Материалы диалога через API

---

.gitignore
builds/_winrar_chrome_pack_zip.bat
builds/_winrar_firefox_jetpack_pack.bat
builds/_winrar_firefox_pack_winrar.bat
builds/_winrar_opera.ext_pack.bat
source/vkopt.js

в основном косметика, но у меня без этого Fold by indent криво работал
нормальный дифф

remove trailing spaces + fixed some indentation

---

background.js
content_script.js

trim trailing space

---

_build.sh
source/vkopt.js

-утечка arguments-

---

source/vklang.js
source/vkopt.js

В старом ВК был белый фон. Есть люди, кому он нравился больше, чем серый сейчас.

Возможность смены фона на белый

---

source/vkopt.js

надеюсь, новый форк каждое обновление не хуже rebase.

скрытие блоков

---

source/vkopt.js

Кнопки с галочками лучше обычных!

ConfigBackupRestore

---

source/vklang.js
source/vkopt.js

[Help wanted] delete from playlist

---

source/vkopt.js

фикс последних эмодзи

---

source/vkopt.js

https://github.com/VkOpt/VkOpt/issues/359#issuecomment-306005469

Fix Profile onLocation

---

source/vkopt.js

Для тестирования через консоль:
https://pastebin.com/GXfB16ac

Старый стиль аудиокнопок

---

_build.sh
builds/_webext_pack.sh

Обновление sh скриптов для webext

---

source/vkopt.js

Убрано ограничение по высоте, чтобы помещались все иконки профиля, добавлен поиск по списку аудио

add search filter for audio list

---

source/vkopt.js

Фикс старых аудиокнопок

---

source/vkopt.js

Чисто как пример. Prefix "gim" — настройки для сообщений сообществ. Еще на иконки можно навешать тултипы. 
Хотел добавить обновление списка диалогов после включения чтения сообщений, но что-то не получилось.

Добавлено отключение тайпинга и чтения сообщений в интерфейс

---

source/vkopt.js

•Фикс тайпинга. 
•Просмотр комментариев с конца (пример реализации). 
"count" и "offset" можно изменить. Потому что в моем случае каждый раз будут подгружаться 3 комментария с ветками (если имеются). Да и мне кажется так будет лучше, чем по 20. Кол-во комментариев первого уровня можно подгрузить и ajax'ом (в общем, как удобно: API или ajax):
var params = {
  act: 'get_post_replies',
  owner_id:  -16925304,       //id profile/group
  item_id: 11079                  //id post
  count: 1
};
ajax.post('al_wall.php', params, {
  onDone: function(replies, names, data) {
    var count = data.count;
  }
});
•Открытие аватарки в полном размере у закрытых страниц.

Фикс + функции. 

---

source/vkopt.js

anonymize name of pinned message

pinned name anonymize

---

source/vklang.js
source/vkopt.js

+ Поиск всех бесед
+ Старая иконка верификации
+ Просмотр "живых" обложек сообществ
+ Переключатель "Себе в личку" в модальном окне репоста
Фикс отображение кнопки просмотра результатов опроса в сообщениях

Небольшие фичи

---

source/vkopt.js

serach parameter is changed from `img_url ` to `url`

Fix Yandex image search

---

source/vkopt.js

Отключение белого шрифта во всплывающем окошке со ссылками для скачивания видео

Белый шрифт ссылок на видео
