VkOpt/VkOpt

source/vk_media.js
Добавление стандартной процедуры зачистки от нечитаемых или непраильно обрабатываемых символов для Wget ссылок.
Как показала практика такая чистка необходима особенно и для Wget ссылок. (К примеру. столкнулся кучу раз с проблемой, что не отрабатывается двоеточие ":" и скачивание не начинается)
=> Чистка имен файлов vkCleanFileName для Wget ссылок.

source/vk_lib.js
Функции работы с настройками - одни из самых вызываемых (особенно getSet), но я нашел несколько ошибок оптимизации:
в функции getSet:
1. переменная sett ни для чего не используется, кроме проверки существования куки.
1. vkgetCookie вызывается излишнее число раз
1. лишняя проверка type==null т.к. !type уже покрывает случай type==null
1. избыточный код из-за различания текущих настроек и настроек по умолчанию в случае, когда они совпадают.
а также:
* в функции setSet и setCfg переменная type неправильно названа. На работу никак не влияет, но путает читателя, т.к. передает неправильный смысл.
* setCfg дублирует функционал setSet
И мне кажется, что хранить настройки в глобальной переменной SettBit лучше бы в виде массива, в уже разделенном виде, чтобы по всему коду не было вызовов split(), …
=> Оптимизация работы с настройками

source/vk_lib.js
Заметил, что после моего коммита из #88 перестало сохраняться состояние галочки "фильтрация". Это из-за того, что setCfg теперь вызывает setSet (я подумал, что код дублируется), а в setSet была ошибка: нельзя изменять символ строки по номеру, обратившись в стиле массива:
`str[i]='c'; // str не меняется`
и видимо до этого всё работало, потому что setSet не использовалась для remixbit настроек. Но так как в ней предусматривалось такое использование, я считаю что нужно исправить и использовать её для изменения всех видов настроек. В том числе в функции vkSwitchSet.
=> Дополнение к #88 (настройки)

source/vk_page.js
Исправлен небольшой косметический баг: когда открываем окно редактирования списка новостей, подсказка о нажатии клавиши Enter сразу висит, и не убирется, пока по ней не проведешь мышкой или не сделаешь какое-нибудь другое действие. То есть если просто открыть и закрыть это окно, подсказка не уберется и будет висеть вечно, до тех пор, пока снова не откроешь это окно  и не проведешь мышкой над подсказкой. 
Поэтому подсказка теперь выводится только при нажатии мышкой на поле поиска. Думаю, этого будет достаточно.
=> Дополнение к #75 (списки новостей)

source/vk_media.js
Исправляю ошибку http://vkopt.net/forum/showthread.php?p=67827#post67827
там сломалась функция скачивания фотографий через формирование страницы из-за #84 
Но убирать `var` я не предлагаю, потому что оставлять весь сгенерированный html в глобальной области как-то расточительно. Вместо этого предлагаю задать onclick через функцию.
=> Исправление формирования страницы с фотками

source/vk_main.js, source/vkopt.js
Добавлена экстра-настройка, позволяющая отключить скачивание хотфиксов.
Не только для параноиков, но и для тех, кто сидит на бете.
=> Настройка хотфиксов

source/vk_settings.js
Исправлена неправильная работа extra-настроек.
Если по умолчанию настройка true, а пользователь её выключает, то тогда она остается выключенной только до перезагрузки страницы. Функция isChecked возвращает пустую строку в случае, если пользователь снял галочку, а VkOpt считает, что если значение настройки - пустая строка, то это какая-то ошибка и это не надо принимать во внимание. И значение настройки остается по умолчанию, т.е. true
=> Исправление работы extra-настрек

source/vk_lib.js, source/vk_media.js
Добавляется функция, с помощью которой можно скачать все фотографии (в том числе "сохраненные") так, что они будут лежать по папкам соответственно альбомам. Кроме того, внутри папок нумерация фотографий идет так же, как в альбоме и имена файлов имеют фиксированную длину (чтобы 10 не шла после 1). Требуется качальщик wget.
На странице альбомов добавляется меню действий:
При нажатии на [ Ссылки ] появляется окошко с прогрессбарами, а потом - текст скрипта и кнопки сохранения:
Любой разработчик может добавить вкладку со скриптом для какого-нибудь другого качальщика, т.к. в функцию генерации скрипта передается объект с названиями альбомов и ссылками на фотки.
=> Функция генерации скрипта для wget для скачивания всех альбомов

source/vk_users.js
Чувак на форуме [пишет](http://vkopt.net/forum/showthread.php?p=68083#post68083):
> Функция "Всплывание фото/информации при наведении на маленькие аватары" глючит. Если наведёшь курсор на аватар, а всплывающая увеличенная картинка в этот момент окажется под курсором, то она будет мигать, особенно это заметно когда открываешь подробности на картинке и наводишь курсором на аватар находящимся в левом части экрана:
У меня тоже такое иногда бывает. Предлагаю решить проблему, показывая всплывашку справа в случае если всплывашка под курсором, потому что тогда будет вышеописанное мигание.
=> Показывать всплывающий аватар справа, если под курсором

source/vk_media.js, source/vk_page.js
Сейчас если щелкать по любому пункту выпадающего списка, то в консоль вываливается ошибка
`TypeError: self.options.updateHeader is not a function`
Нужно заменить везде updateHeader на updateTarget, и тогда ошибки не будет.
=> Исправление для выпадающего списка

source/vk_media.js
На Опере 12 и др. старых браузерах нет поддержки сохранения Blob, поэтому дополнительно подключаем библиотеку эмуляции Blob через data:
а также добавлена проверка, есть ли возможность вообще сохранять файлы, чтобы не выводить ссылку на функцию в неподдерживаемых браузерах.
=> Поддержка старых браузеров в функции сохранения Zip архива с фотками

source/vk_media.js
При поиске по аудио если выбрать поиск "по исполнителю", то кнопка "ссылки" выдает результат, как будто "по композиции". Исправлено добавлением параметра к запросу.
=> Cсылки на аудио: поиск по исполнителю

background.js
Сейчас если нажать на кнопку скачивания в Firefox, закачка не начинается. А после перезапуска браузера начинается. Дело в том, что в 36 версии [изменена saveURI](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIWebBrowserPersist#saveURI%28%29)
=> Исправление для скачивания аудио на Firefox

source/vk_page.js
Исправлено некорректное поведение блокировщика рекламы при наличии пустых правил (типа запятой в конце, начале, или две подряд)
А также trim() и toLocaleLowerCase() перенесены в подготовительный этап, потому что правил будет явно меньше, чем новостей в ленте.
=> Дополнение для блокировщика рекламы: пустые правила

source/vk_media.js
Довелось мне тут недавно на Windows скачать скрипт для скачивания аудио через wget. И у меня скачался файл playlist.bat.txt (Windows7, Firefox 37) - видимо, защита какая-то, чтобы батники просто так не скачивались. Если поменять mime-тип на `application/x-download`, то скачивается .bat
=> Другой MIME для плейлистов .bat

source/vk_lib.js, source/vk_settings.js, source/vklang.js, source/vkopt.js
Добавляется настройка на вкладку "остальное", называется "Использовать HTML5 для сохранения файлов".
Вместо подгрузки флешки подгружается библиотека FileSaver.js, а когда saveAs будет реализована нативно, вообще ничего подгружаться не будет.
=> Сохранять файлы используя HTML5

source/vk_lib.js
Если `vkLdr.show()` вызывается при открытом каком-то всплывающем окне, то при `vkLdr.hide()` закрываются все окна, и еще остается черный прозрачный фон. Нужно `hideAll` поменять на `hideLast`
=> Улучшение vkLdr

source/vk_page.js
Сортирует загруженные посты на странице группы или паблика по количеству лайков по убыванию.
Еще можно было сделать, чтобы при проматывании стены вниз (при подгрузке новых постов) автоматически запускалась сортировка
=> Сортировка стен групп и пабликов по лайкам

source/vk_media.js, source/vk_settings.js, source/vklang.js, source/vkopt.js
Сейчас HTML5 плеер используется для воспроизведения аудиозаписей только на компьютерах с Flash-плеером версии меньше 9 и на маках.
Новая настройка даёт возможность использовать HTML5 плеер принудительно.
_у меня, правда не сразу заработало - надо было обновить libav-tools и libavutil54_
=> Принудительно использовать HTML5 аудио плеер

source/vk_media.js
Сейчас, если играет песня из сборника, то в качестве исполнителя на панели информации об альбоме написано "Various Artists", и во всех ссылках тоже, и в "мне повезёт". Естественно, поиск по аудио с такими названиями не работает.
[Например](https://vk.com/audio?q=%D0%90%D0%BD%D0%94%D0%B5%D0%BC%20%E2%80%93%20%D0%90%D0%BD%D1%82%D0%B8%D1%85%D1%80%D0%B8%D1%81%D1%82)
=> Исправление поиска last.fm для сборников

source/vk_media.js
Когда в аудиозаписях справа подгружается инфа об альбоме, выводим не просто его название, а еще и ссылку на Last.fm
=> Добавлена ссылка на альбом на last.fm

source/vk_lib.js, source/vk_media.js
В окне "материалы беседы" на вкладке "фотографии" появляется ссылка:
Пока что только фотографии, с остальными там сложнее будет.
Последовательно загружается wkview.php и парсятся адреса фоток. И показывается окошко с табами "ссылки" и "ссылки для wget". Имена файлов - числа с фиксированной длинной (5 символов, думаю должно хватить). Считаю это лучше чем id фоток, потому что фотки могут быть от разных владельцев и вообще я хочу видеть такой же порядок, как в диалоге.
И еще добавил в vkbrowser определение ОС Linux, чтобы ставить соответствующее расширение у файла со ссылками для wget. Потому что, во-первых, текст там будет один и тот же (русских символов нет), а во-вторых мой предыдущий аргумент про скачивание скрипта на win и закидывание на сервер под nix в данном случае не применим. 
И …
=> Функция скачивания всех фоток из диалога

source/vk_main.js, source/vk_page.js, source/vk_settings.js, source/vklang.js
Есть такой сайт, [Пикабу](http://pikabu.ru). Там выкладываются интересные и развлекательные картинки. Мне нравится, как там сделан переход (прокрутка) от одного поста к другому - вверху справа есть кнопки "следующий" и "предыдущий", при нажатии на которые страница прокручивается так, что следующий (предыдущий) пост сразу оказываются под верхней границей окна браузера. Т.е. прокручивание колесиком мышки заменяется на один щелчок. А также эта функция срабатывает при нажатии на кнопки клавиатуры A (предыдущий) и D (следующий).
Я сделал, чтобы таким же образом можно было листать "новости" и стены групп, пабликов и профилей. Дизайн нагло украл у Пикабу, правда реализовал его через CSS, а не картинками.
Еще на Пикабу к клавиатуре привязаны другие действия, например на кнопки W и S привязаны …
=> Кнопки быстрого перехода к постам

source/vk_page.js
На маленьких экранах кнопки листания постов закрывают шапку сайта. Поэтому в самом верху надо их скрывать.
z-index изменен на 499 для совместимости с темой Neo.
=> Дополнение к #130: скрывать кнопки в верху страницы

source/vk_page.js
Я нашел баг в кнопках быстрого перехода к постам.
В случае, если включена фильтрация ленты новостей, и если присутствует отфильтрованный пост, и он находится выше, чем видимая область страницы, кнопка "предыдущий" не работает.
Потому что почему-то `getBoundingClientRect()` возвращает объект с нулями для невидимых элементов, хотя по-моему логичнее было бы возвращать null или объект с null-ами.
и еще добавлено удаление событий keydown перед добавлением. потому что при переходе с профиля в новости или с новостей на профиль новый обработчик не заменяет старый, а добавляется, причем при нажатии на клавиши отрабатывает только старый. Тоже мутная история, короче. Вообще лучше найти способ удаления только старого обработчика, а то вдруг там еще какие-то будут. Но пока и так сойдет.
=> Дополнение к #130: при наличии вверху отфильтрованных постов

source/vk_main.js
Исправление стилей налезающего поля для id аудио+видео. Они идут последовательно друг с другом и одно поле можно перекрыть другое.
Из-за постоянного размера высоты в 25px поле для ввода id аудио/видео может налезть на поле для поиска (в компактных стилях, vkfix например). Лучше пусть оно будет стандартного размера. В обычном режиме все нормально и без этого значения.
Налезает в компактном: http://savepic.org/7327940.png
Обычный режим (без 25px высоты): http://savepic.org/7317700.png
Для фото неактуально, поскольку строка поиска далеко от поля ввода id.
=> Исправление налезающего поля для id аудио+видео

source/vk_users.js
Исправлена проблема, когда заходишь в группу, в раздел Участники, потом вызываешь юзер-меню,  потом жмёшь на галочку рядом с "Страница", и потом на крестик (закрыть). Закрываются все всплывашки, и остается черный фон, с которым ничего не сделать.
Ошибка аналогична #124
=> Исправление vkPopupAvatar

source/vk_users.js
Встречаются некоторые ссылки на vk.com, которые ведут не на профиль. Для таких ссылок всплывающий профиль показывает данные для профиля с коротким именем undefined. Я считаю, что для таких ссылок не надо показывать всплывающий профиль.
=> Не показывать всплывающий профиль undefined

source/vk_page.js
Не работает ссылка "[Код]" на вики странице. Не знаю, как на остальных, но у меня не сработала на https://vk.com/page-38495633_46849882
=> Исправление для кода вики страниц

source/vk_lib.js, source/vk_main.js, source/vk_media.js
В окне со списком вики-страниц появляется ссылка для скачивания ZIP-архивом всех страниц в виде html:
Страницы скачиваются вместе с картинками, которые конвертируются в inline data:uri
Функция может пригодиться, когда в группе выкладывают полезные инструкции в виде вики-страниц. Берешь, скачиваешь, скидываешь на телефон например и всё, независимый от интернета комплект мануалов всегда с тобой.
Также немного изменена функция отображения самого списка: к ссылкам добавлен класс `vk_wiki_link` и дополнительный атрибут `pid`, потому что было бы глупо снова запрашивать список страниц, когда вот они все уже лежат, да и парсить id страниц из href как-то не комильфо.
И еще я извлек функции подгрузки внешних библиотек, чтобы их удобнее было использовать в других функциях. гибкость, короче.
=> Функция массового скачивания вики-страниц

source/vk_main.js
возвращена `vkLinksUnescapeCyr` и обёрнуто в try, потому что при исходящем сообщении ссылка кодируется в UTF-8, а при входящем - в CP1251
=> Обход away для русских ссылок

source/vk_page.js
Некоторые темы оформления фиксируют шапку сайта, и поэтому кнопки листания постов проматывают верхушку поста под шапку, и она перекрывает.
=> Дополнение к #130: совместимость со стилями, фиксирующими шапку

background.js, builds/firefoxJetpack/resources/vkopt/lib/main.js
Исправление для джетпака, чтобы на HTTP соединении не появлялась ошибка "epic fail".
Каждому сообщению будет добавляться идентификатор - время отправки запроса. Думаю, время в миллисекундах можно использовать в качестве идентификатора.
За наводку спасибо @Evengard
=> #110 - Исправление синхронизации потоков для джетпака

source/vk_main.js, source/vk_settings.js, source/vklang.js, source/vkopt.js
Когда в "диалогах" пишешь сообщение, и вставляешь ссылку, при отправке она превратится в картинку во весь экран диалога, с заголовком и текстом. Причем крестика для удаления этой миниатюры нет, как на стенах. Мне это не нравится, поэтому предлагаю функцию отключения этой "мега-фичи".
Стены не затрагивает, только диалоги. 
Настройка находится на вкладке "Сообщения".
=> Функция, отключающая преобразование ссылок в диалогах в миниатюры

source/vk_main.js
У меня в новостях появилось видео, я нажимаю на него (на картинку, с кнопкой "плей"), и оно воспроизводится через Flash. Оказывается, там другой параметр передается при воспроизведении не со страницы видео. Не знаю, было так или нет, но теперь есть.
=> HTML5 видео плеер в "новостях"

source/vk_media.js
`photoview.canFullscreen` неправильно работает только на Opera 12, поэтому вносить изменения можно только на этом браузере, а на остальных можно оставить, как было.
=> Изменение photoview.canFullscreen только на Opera 12

source/vk_main.js, source/vk_media.js, source/vk_page.js
В коде часто встречается ситуация, когда модифицируется функция ВК, а проверка соответствующей настройки идет уже потом, при срабатывании модифицированной функции. Я считаю, что лучше при выключенной настройке вообще не модифицировать функции ВК, к тому же методы класса Inj самые медленные, поэтому отключение функций ускорит работу.
=> Уменьшение вызовов Inj при отключенных настройках

source/vk_page.js, source/vk_settings.js, source/vklang.js
Теперь возможно отключить функцию добавления фильтра по типам на странице "Мои группы".
Номер настройки взял 23, он не числился свободным, но его использования я не нашел.
=> Настройка для функции добавления фильтра на странице "Группы"

source/vk_media.js, source/vkopt.js
Предлагаю создать настройку для фичи, при которой по щелчку на "Фотография 1 из 40" переключается режим "подгонять/не подгонять фото в просмотрщике по высоте под высоту видимой области". Я об этой фиче не знал, да она мне и не нужна, однако для неё делается 3 модификации функций ВК.
Текст придумать сложно, но пока такой: 
`При щелчке на "Фотография 1 из 40" не подгонять фото под высоту экрана`
=> Фича "При щелчке на Фотография 1 из 40" вынесена в настройки

source/vk_main.js
Оказалось, что введенная мною функция отключения преобразования ссылок в миниатюры отключает вообще все преобразования, т.е. вставить картинку по URL тоже нельзя. Исправляюсь.
=> Исправление для #163

background.js
Позволяет кроссдоменно отправлять файлы в виде массива байтов.
=> Не сериализовывать массивы при отправке

source/vk_users.js
У меня случается такая шняга: я хочу нажать на какую-нибудь ссылку-аватарку (человек или группа), чтобы перейти на страницу. И после перехода в левом верхнем углу появляется всплывающий профиль. И приходится специально навести-увести курсор с него, чтобы он пропал.
Происходит следующее: я навожу курсор на аватарку, начинает грузиться профиль через API, я щелкаю на аватарку, страница открывается, а после этого профиль только загрузился, и всплывает в позиции 0, 0. Причем сам элемент-ссылка всё еще существует и даже isVisible возвращает true. 
Скриншот:
=> Не показывать всплывающий профиль после клика

source/vklang.js
Ошибка в тексте когда прикрепляешь аудио по id. Вместо audio написано video.
=> Ошибка в английском ленге

source/vk_lib.js
В ветке `if (response.error)` это же условие проверяется снова. Очевидно, оно всегда будет истинным, т.к. response.error не изменяется. Поэтому вторая проверка бессмысленна.
=> Лишний код в call

source/vk_face.js, source/vk_lib.js, source/vk_page.js, source/vk_users.js
В функциях календаря и проверки друзей в качестве строкового представления JSON-объекта используется часть ответа от сервера, и там свойства, состоящие только из чисел, не берутся в кавычки (почему? не знаю. Разработчики безалаберные, не следуют стандарту).
Поэтому эти функции не работают. Исправлено возвращением использования `eval` (в адаптированной форме)
А также исправлена JS-реализация метода JSON.parse, чтобы она не затрагивала глобальную область.
=> Замена JSON.parse на ev41

source/vk_lib.js, source/vk_main.js, source/vk_media.js
Некоторые функции требуют продолжительного времени, когда надо сидеть и смотреть на прогрессбары. Было бы удобнее, если бы диалоговые окна можно было свернуть, чтобы выполнение задания продолжалось в фоне.
Предлагаю использовать для этого видеоплеер, где уже реализована функция сворачивания. В функции `vkAlertBox` добавлен пятый параметр, определяющий, показывать ли контент в видео плеере или как раньше, в MessageBox-е. А также новый метод отображения задействован в 3-х функциях (для пробы): список wiki-страниц, сохранение переписки и получение ссылок на все фото пользователя.
Скриншот в свернутом состоянии:
Можно менять размер, перетаскивать, как видеоплеер. При клике на ссылки внутри свернутого окошка, открываются страницы, а окошко остается.
Кстати, в такое окошко можно запихнуть и …
=> Диалоговые окна с возможностью сворачивания

source/vk_page.js
Если в администрируемой группе нет ни одного фотоальбома,  в функции `vkModGroupBlocks` случается ошибка и дальше выполнение не идёт, и кнопки просмотра wiki-страниц и др. не добавляются.
=> Исправление  исчезающих кнопок в группах

source/vk_media.js
Из-за [изменений](https://github.com/Pmmlabs/vk_mirror/commit/e9792479f12b54b751ff610f225e410151ddffec#diff-011f875d8d312e5506a7668224bf8246) Вконтакте вставка картинок из буфера перестала работать.
Исправлено в соответствии с новым кодом.
=> Исправление вставки картинок из буфера в ФФ

source/vk_media.js
В именах файлов не заменяются `<` и `>`, потому что их сначала надо декодировать из html-entities, а уже потом заменять.
=> Поменять местами winToUtf и vkCleanFileName

source/vk_lib.js
Неизвестные для 1251 символы превращать в подчеркивания, а не в вопросики, потому что они потом вылазят в именах файлов, где не допускаются.
=> Неизвестный для 1251 символ

source/vk_media.js, source/vk_page.js
В скриптах wget для Linux надо заменять <kbd>\`</kbd> на `'` в именах файлов.
На Windows этот символ можно оставить, он разрешается
=> Замена ` на ' в скриптах wget

source/vk_page.js
Дополнение к #130 
Когда нажимаем кнопку "предыдущий", а предыдущий скрыт фильтром рекламы, страница перематывается на самый верх, потому что для скрытых элементов top будет 0.
=> Исправление бага в кнопках перемотки постов

source/vk_main.js
Дополнение к #223 
Оказалось, что при включенной функции "Использовать плеер Youtube для видео с Youtube" нет кнопки "полноэкранный режим". Так что возвращаем.
=> Youtube полноэкранный режим

source/vk_users.js
Если у группы сайт содержит `http://`, то ссылка во всплывающем профиле получается неправильная. Убираем протокол из ссылки.
=> Исправление ссылки на сайт в быстром профиле группы

source/vk_main.js
Исправление для #223 
При включенной опции "Использовать плеер Youtube для видео с Youtube" кнопка "свернуть" работала некорректно, из-за того, что замена кода была неглобальной.
=> Сворачивание видео с Youtube

builds/_chrome_pack.sh
Для упаковки хромовского расширения использовать python. Кстати, размер zip файла получается меньше, чем при упаковке WinRar-ом.
=> Cкрипт python для паковки расширения для Chrome

source/vk_face.js, source/vk_media.js
Решение для #236
Иногда элементы строки аудиозаписи расползаются, особенно видно в Firefox при определенном масштабе, видимо относительные размеры элементов неправильно рассчитываются.
Кнопка скачивания аудиозаписи перенесена в блок с информацией, так что теперь его размеры изменяться не будут и элементы прыгать тоже не будут.
=>  Исправление прыгающих элементов аудио

source/vk_main.js
Исправление для #221 
Если начать загрузку документа, свернуть окно, перейти на другую страницу, и потом загрузка заканчивается, то документ сохранить нельзя, потому что нужные функции удалены функцией `nav.go`. Поэтому надо их прикопать.
Для аудио всё ок.
=> Исправление для сворачивания окон: документы

source/vk_page.js
Блокировщик рекламы в ленте не блокировал записи, если рекламный пост репостнут с добавлением нерекламного текста.
Потому что проверялся только первый элемент `wall_post_text`, а надо проверять все.
`return false` написано для остановки перебора функцией `each`
=> Исправление адблока для репостов

source/vk_page.js
Для ветки amo.
`val` - это функция ВК, так что называть переменные так нельзя.
Переименовано на `value`.
=> Замена val на value

source/vk_main.js, source/vk_page.js, source/vk_users.js
Теперь при включенной опции "Возможность сворачивать некоторые диалоговые окна" (#210) будет возможность свернуть окна:
* получения Wiki-кода страницы
* просмотра результатов опроса
* всплывающих профилей (и групп)
=> Больше сворачиваемых окон

source/vk_page.js
Исправление для #164 
В новогоднюю ночь все посты на стенах стали прошлогодними, но в серых подписях (там, где дата) номер года не появился. Наверное, он появляется у постов старше определенного срока, а не у прошлогодних постов.
Вследствие чего все посты со всех стен вставились в начало ленты (т.к. год их публикации распознался как 2016)
Поэтому исправление: если год не указан, и месяц поста больше текущего, то от текущего года отнять один.
=> Новогоднее исправление для подписок на стены

_config.yml, source/vklang.js, source/vkopt.js
Среди личных сообщений трудно найти записи из групп или пересланные сообщения. Поиск по ним не ведется, кнопка "Показать вложения" отображает только картинки, аудио-видео, документы, к тому же, не позволяет переходить непосредственно к сообщению.
Данный модуль добавляет кнопку "Ссылки и репосты" в окно вложений  (диалог кнопка "Показать вложения").
При нажатии на нее отображается история wall, link, forward . Клик на дату позволяет перейти к нужному сообщению в диалоге, или сразу к записи в группе.
Пример:
Еще пример:
=> Модуль позволяет просматривать репосты, ссылки, форварды, в выбранном диалоге

source/vkopt.js
При отключении показа кнопок, считаю, что лучше будет значения опций приводить к false. 
Забыли про настройки отображения кнопок в сообщениях сообщества. 
Исправление наложения кнопки:
Выбрал 150px, потому что потом неудобно мышью ставить курсор в конец строки.
=> Поправки к кнопкам блокировки отчётов об прочтении и наборе сообщений

source/vkopt.js
Часто возникает необходимость иметь бэкап сообщений в машиночитаемом формате (в идеале JSON), для дальнейшего анализа.  
Этот MR добавляет функцию экспорта истории переписки в формате json (`get_history_json`) и соответствующую кнопку в диалоге сохранения сообщения
Не заморачивался с формированием имени файла, по-моему так достаточно, если кто-то думает иначе, исправлю.
=> Export vk messages as json
